import Bounds from './Bounds';
import LngLat from './common/LngLat';
import BasemapToggle from './control/BasemapToggle';
import BMapGallery from './control/BMapGallery';
import Compass from './control/Compass';
import Fullscreen from './control/Fullscreen';
import Home from './control/Home';
import LayerListControl from './control/LayerListControl';
import MeasureArea from './control/MeasureArea';
import MeasureLine from './control/MeasureLine';
import UndergroundSwitch from './control/UndergroundSwitch';
import Zoom from './control/Zoom';
import Map from './Map';
import FeatureReduction from './Overlays/FeatureReduction';
import Icon from './Overlays/Icon';
import Label from './Overlays/Label';
import Marker from './Overlays/Marker';
import OverlayGroup from './Overlays/OverlayGroup';
import Polygon from './Overlays/Polygon';
import Polyline from './Overlays/Polyline';
import Size from './Overlays/Size';
import MapEvent from './utils/MapEvent';
declare const _default: {
    Bounds: typeof Bounds;
    LayerListControl: typeof LayerListControl;
    Zoom: typeof Zoom;
    Home: typeof Home;
    Compass: typeof Compass;
    Fullscreen: typeof Fullscreen;
    MeasureArea: typeof MeasureArea;
    MeasureLine: typeof MeasureLine;
    BasemapToggle: typeof BasemapToggle;
    BMapGallery: typeof BMapGallery;
    UndergroundSwitch: typeof UndergroundSwitch;
    Marker: typeof Marker;
    Icon: typeof Icon;
    Size: typeof Size;
    Label: typeof Label;
    FeatureReduction: typeof FeatureReduction;
    OverlayGroup: typeof OverlayGroup;
    LngLat: typeof LngLat;
    Polyline: typeof Polyline;
    Polygon: typeof Polygon;
    MapEvent: typeof MapEvent;
    Map: typeof Map;
};
export default _default;
